import type { AppLanguage } from "./types";
import type { AppTranslations } from "./translations";

export const finalModuleTranslations: Record<AppLanguage, Pick<AppTranslations, "history" | "maintain" | "userCenter" | "audit">> = {
  es: {
    history: { title: "Historial", deviceHistoryData: "Historial de datos del dispositivo", deviceId: "ID dispositivo", deviceName: "Nombre dispositivo", deviceType: "Tipo de dispositivo", productModel: "Modelo de producto", company: "Empresa", reportTime: "Fecha reporte", reportType: "Tipo de reporte", realtimeData: "Datos en tiempo real", supplementaryData: "Datos suplementarios", longitude: "Longitud", latitude: "Latitud", address: "Direccion", lockStatus: "Estado de candado", shackleStatus: "Estado de grillete", battery: "Bateria", signal: "Senal", temperature: "Temperatura", speed: "Velocidad", firmwareVersion: "Version de firmware", rawPayload: "Payload original", viewOnMap: "Ver en mapa", detail: "Detalle", export: "Exportar", search: "Buscar", reset: "Restablecer", columnSettings: "Configurar columnas" },
    maintain: { title: "Mantenimiento", firmware: "Firmware", ota: "OTA", diagnosis: "Diagnostico", upload: "Subir", firmwareUpload: "Subir firmware", firmwareType: "Tipo de firmware", masterMcu: "Master MCU", bluetoothMcu: "Bluetooth MCU", extensionMcu: "Extension MCU", selectFile: "Seleccionar archivo", versionName: "Nombre de version", description: "Descripcion", uploadTime: "Fecha de subida", upgrade: "Actualizar", batchUpgrade: "Actualizacion por lote", selectUpgradeFile: "Seleccionar archivo de actualizacion", upgradeRecord: "Registro de actualizacion", currentFirmwareVersion: "Version actual de firmware", targetFirmwareVersion: "Version destino", progress: "Progreso", diagnosisType: "Tipo de diagnostico", logLevel: "Nivel de log", summary: "Resumen", fullLog: "Log completo", downloadLog: "Descargar log", search: "Buscar", reset: "Restablecer", export: "Exportar", detail: "Detalle", delete: "Eliminar", confirm: "Confirmar", cancel: "Cancelar" },
    userCenter: { title: "Centro de usuarios", organization: "Organizacion", permission: "Permisos", user: "Usuarios", addCompany: "Agregar empresa", companyName: "Nombre de empresa", contact: "Contacto", email: "Correo", phone: "Telefono", affiliatedCompany: "Empresa asociada", timezone: "Zona horaria", developerId: "Developer ID", developerKey: "Developer key", pushStatus: "Estado de push", addRole: "Agregar rol", roleName: "Nombre del rol", roleDescription: "Descripcion del rol", permissionSetting: "Configuracion de permisos", assign: "Asignar", reset: "Restablecer", addUser: "Agregar usuario", username: "Usuario", nickname: "Nombre", phoneNumber: "Numero de telefono", role: "Rol", password: "Contrasena", confirmPassword: "Confirmar contrasena", accountStatus: "Estado de cuenta", changePassword: "Cambiar contrasena", search: "Buscar", add: "Agregar", edit: "Editar", delete: "Eliminar", enable: "Habilitar", disable: "Deshabilitar", confirm: "Confirmar", cancel: "Cancelar" },
    audit: { title: "Auditoria", user: "Usuario", company: "Empresa", action: "Accion", module: "Modulo", description: "Descripcion", ipAddress: "Direccion IP", userAgent: "User agent", createdTime: "Fecha creacion", export: "Exportar", search: "Buscar", reset: "Restablecer" },
  },
  en: {
    history: { title: "History", deviceHistoryData: "Device history data", deviceId: "Device ID", deviceName: "Device name", deviceType: "Device type", productModel: "Product model", company: "Company", reportTime: "Report time", reportType: "Report type", realtimeData: "Real-time data", supplementaryData: "Supplementary data", longitude: "Longitude", latitude: "Latitude", address: "Address", lockStatus: "Lock status", shackleStatus: "Shackle status", battery: "Battery", signal: "Signal", temperature: "Temperature", speed: "Speed", firmwareVersion: "Firmware version", rawPayload: "Raw payload", viewOnMap: "View on map", detail: "Detail", export: "Export", search: "Search", reset: "Reset", columnSettings: "Column settings" },
    maintain: { title: "Maintain", firmware: "Firmware", ota: "OTA", diagnosis: "Diagnosis", upload: "Upload", firmwareUpload: "Firmware upload", firmwareType: "Firmware type", masterMcu: "Master MCU", bluetoothMcu: "Bluetooth MCU", extensionMcu: "Extension MCU", selectFile: "Select file", versionName: "Version name", description: "Description", uploadTime: "Upload time", upgrade: "Upgrade", batchUpgrade: "Batch upgrade", selectUpgradeFile: "Select upgrade file", upgradeRecord: "Upgrade record", currentFirmwareVersion: "Current firmware version", targetFirmwareVersion: "Target firmware version", progress: "Progress", diagnosisType: "Diagnosis type", logLevel: "Log level", summary: "Summary", fullLog: "Full log", downloadLog: "Download log", search: "Search", reset: "Reset", export: "Export", detail: "Detail", delete: "Delete", confirm: "Confirm", cancel: "Cancel" },
    userCenter: { title: "User Center", organization: "Organization", permission: "Permission", user: "User", addCompany: "Add company", companyName: "Company name", contact: "Contact", email: "Email", phone: "Phone", affiliatedCompany: "Affiliated company", timezone: "Timezone", developerId: "Developer ID", developerKey: "Developer key", pushStatus: "Push status", addRole: "Add role", roleName: "Role name", roleDescription: "Role description", permissionSetting: "Permission setting", assign: "Assign", reset: "Reset", addUser: "Add user", username: "Username", nickname: "Name", phoneNumber: "Phone number", role: "Role", password: "Password", confirmPassword: "Confirm password", accountStatus: "Account status", changePassword: "Change password", search: "Search", add: "Add", edit: "Edit", delete: "Delete", enable: "Enable", disable: "Disable", confirm: "Confirm", cancel: "Cancel" },
    audit: { title: "Audit", user: "User", company: "Company", action: "Action", module: "Module", description: "Description", ipAddress: "IP address", userAgent: "User agent", createdTime: "Created time", export: "Export", search: "Search", reset: "Reset" },
  },
  zh: {
    history: { title: "历史记录", deviceHistoryData: "设备历史数据", deviceId: "设备ID", deviceName: "设备名称", deviceType: "设备类型", productModel: "产品型号", company: "公司", reportTime: "上报时间", reportType: "上报类型", realtimeData: "实时数据", supplementaryData: "补充数据", longitude: "经度", latitude: "纬度", address: "地址", lockStatus: "锁状态", shackleStatus: "锁梁状态", battery: "电量", signal: "信号", temperature: "温度", speed: "速度", firmwareVersion: "固件版本", rawPayload: "原始数据", viewOnMap: "地图查看", detail: "详情", export: "导出", search: "搜索", reset: "重置", columnSettings: "列设置" },
    maintain: { title: "维护", firmware: "固件", ota: "OTA", diagnosis: "诊断", upload: "上传", firmwareUpload: "上传固件", firmwareType: "固件类型", masterMcu: "主MCU", bluetoothMcu: "蓝牙MCU", extensionMcu: "扩展MCU", selectFile: "选择文件", versionName: "版本名称", description: "描述", uploadTime: "上传时间", upgrade: "升级", batchUpgrade: "批量升级", selectUpgradeFile: "选择升级文件", upgradeRecord: "升级记录", currentFirmwareVersion: "当前固件版本", targetFirmwareVersion: "目标固件版本", progress: "进度", diagnosisType: "诊断类型", logLevel: "日志级别", summary: "摘要", fullLog: "完整日志", downloadLog: "下载日志", search: "搜索", reset: "重置", export: "导出", detail: "详情", delete: "删除", confirm: "确认", cancel: "取消" },
    userCenter: { title: "用户中心", organization: "组织", permission: "权限", user: "用户", addCompany: "添加公司", companyName: "公司名称", contact: "联系人", email: "邮箱", phone: "电话", affiliatedCompany: "所属公司", timezone: "时区", developerId: "开发者ID", developerKey: "开发者密钥", pushStatus: "推送状态", addRole: "添加角色", roleName: "角色名称", roleDescription: "角色描述", permissionSetting: "权限设置", assign: "分配", reset: "重置", addUser: "添加用户", username: "用户名", nickname: "姓名", phoneNumber: "电话号码", role: "角色", password: "密码", confirmPassword: "确认密码", accountStatus: "账号状态", changePassword: "修改密码", search: "搜索", add: "添加", edit: "编辑", delete: "删除", enable: "启用", disable: "禁用", confirm: "确认", cancel: "取消" },
    audit: { title: "审计", user: "用户", company: "公司", action: "操作", module: "模块", description: "描述", ipAddress: "IP地址", userAgent: "用户代理", createdTime: "创建时间", export: "导出", search: "搜索", reset: "重置" },
  },
};
