import type { GisSection } from "../../i18n/translations";
import type { AppLanguage } from "../../i18n/types";

export function getGisText(language: AppLanguage, current?: GisSection): GisSection {
  if (current) return current;
  if (language === "zh") {
    return {
      title: "GIS / 电子围栏",
      breadcrumbHome: "首页",
      breadcrumbGis: "GIS",
      breadcrumbGeoFence: "电子围栏",
      breadcrumbFenceRecord: "围栏记录",
      fenceName: "围栏名称",
      sendFence: "发送围栏",
      batchDelete: "批量删除",
      fenceList: "围栏列表",
      deviceFencesAndRules: "设备围栏和规则",
      selectFenceType: "请选择要绘制的围栏类型：",
      polygon: "多边形",
      circle: "圆形",
      searchLocation: "搜索位置或路线",
      noData: "无数据",
      modify: "修改",
      delete: "删除",
      confirm: "确认",
      cancel: "取消",
      saveFence: "保存围栏",
      selectDevice: "选择设备",
      getFenceRuleInfo: "获取围栏和规则信息",
      deviceList: "设备列表",
      block: "区块",
      block1: "区块 1",
      fenceRecord: "围栏记录",
      all: "全部",
      online: "在线",
      offline: "离线",
      view: "查看",
      rules: "规则",
      status: "状态",
      operate: "操作",
      deviceId: "设备 ID",
      deviceName: "设备名称",
      createTime: "创建时间",
      search: "搜索",
      reset: "重置",
      stopSending: "停止发送",
      resend: "重新发送",
      viewDetail: "查看详情",
      stop: "停止",
      sendingProgress: "发送进度",
      queryType: "查询类型",
      storageBlock: "存储区块",
      result: "结果",
      clearResult: "清除结果",
      confirmDeleteFence: "此操作将永久删除围栏。是否继续？",
      offlineWarning: "设备离线。命令将保持待处理或可能失败。",
      remoteWarning: "启用此规则后，设备在围栏外不能远程解封。",
    };
  }
  return {
    title: "GIS / Geo-Fence",
    breadcrumbHome: "Home",
    breadcrumbGis: "GIS",
    breadcrumbGeoFence: "Geo-Fence",
    breadcrumbFenceRecord: "Fence Record",
    fenceName: "Fence name",
    sendFence: "Send fence",
    batchDelete: "Batch delete",
    fenceList: "Fence List",
    deviceFencesAndRules: "Device fences and rules",
    selectFenceType: "Please select fence type to draw:",
    polygon: "Polygon",
    circle: "Circle",
    searchLocation: "Search location, find route",
    noData: "No Data",
    modify: "Modify",
    delete: "Delete",
    confirm: "Confirm",
    cancel: "Cancel",
    saveFence: "Save fence",
    selectDevice: "Select device",
    getFenceRuleInfo: "Get fence and rule information",
    deviceList: "Device List",
    block: "Block",
    block1: "Block 1",
    fenceRecord: "Fence Record",
    all: "All",
    online: "Online",
    offline: "Offline",
    view: "View",
    rules: "Rules",
    status: "Status",
    operate: "Operate",
    deviceId: "Device ID",
    deviceName: "Device name",
    createTime: "Create time",
    search: "Search",
    reset: "Reset",
    stopSending: "Stop sending",
    resend: "Resend",
    viewDetail: "View detail",
    stop: "Stop",
    sendingProgress: "Sending progress",
    queryType: "Query type",
    storageBlock: "Storage block",
    result: "Result",
    clearResult: "Clear result",
    confirmDeleteFence: "This operation will permanently delete the geo-fence. Continue?",
    offlineWarning: "The device is offline. The command will remain pending or may fail.",
    remoteWarning: "If this rule is active, the device cannot be remotely unsealed outside the geo-fence.",
  };
}
